export const selector: string;
export const name: string;
export const attributes: string;
export const type: string;
export const value: string;
export const showMore: string;
export const clickable: string;
export const gradient: string;
export const hide: string;
